### ISSUE TITLE
MCP2515 support

### ISSUE THREAD

**Issue by GreenEllipsis** [DanielMartensson/Open-SAE-J1939#2]
Daniel,
Thanks for doing this. Fills a large open-source gap. I'm planning to use an ATMEGA 328P with an MCP2515 CAN controller. It looks like currently the only supported controller is QT USB. Is this correct?

**Comment by DanielMartensson** [comment]
> Daniel, Thanks for doing this. Fills a large open-source gap. I'm planning to use an ATMEGA 328P with an MCP2515 CAN controller. It looks like currently the only supported controller is QT USB. Is this correct?

Hello!

The C code supports all hardware because the C code does not take account on which hardware you are using.

But for the hardware layer, it's user specific. That means you need to implement the hardware layer. 

In the MCP2515 case, just send the unsigned 32 byte ID and the usigned 8 byte DATA array to the MCP2515 and it will handle the rest.
